name: Crowdin Upload

on:
  push:
    paths:
      - 'po/mmex.pot'
    branches: 
      - master

jobs:
  crowdin-upload:
    if: github.repository_owner == 'moneymanagerex'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin push
        uses: crowdin/github-action@v2.4.0
        with:
          upload_sources: true
          upload_translations: true
          crowdin_branch_name: master
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
